CREATE TABLE User(
	UserID INTEGER PRIMARY KEY AUTOINCREMENT, 
	Firstname TEXT NOT NULL, 
	Lastname TEXT NOT NULL, 
	Email TEXT NOT NULL UNIQUE, 
	Password TEXT NOT NULL
);

CREATE TABLE Advert(
	AdvertID INTEGER PRIMARY KEY AUTOINCREMENT,
	AdvertUserID INTEGER NOT NULL,
	Kind TEXT NOT NULL,
	Category TEXT NOT NULL,
	Description TEXT NOT NULL,
	FOREIGN KEY (AdvertUserID) REFERENCES User(USERID)	
);

CREATE TABLE Address(
	AddressID INTEGER PRIMARY KEY AUTOINCREMENT,
	Street TEXT NOT NULL,
	Postcode TEXT NOT NULL,
	City TEXT NOT NULL,
	Country TEXT NOT NULL
);

CREATE TABLE AdvertAddress(
	Address INTEGER NOT NULL,
	Advert INTEGER NOT NULL,
	FOREIGN KEY (Address) REFERENCES Address(AddressID),
	FOREIGN KEY (Advert) REFERENCES Advert(AdvertID),
	PRIMARY KEY (Address, Advert)
);